name: Minikube Github Action
description: Setup Minikube and starts local cluster
author: hiberbee
branding:
  icon: anchor
  color: blue
inputs:
  minikube-version:
    default: 1.12.3
    description: Set minikube version
    required: false
  kubernetes-version:
    default: 1.18.8
    description: Set Kubernetes version
    required: false
  profile:
    default: minikube
    description: Set minikube profile name
    required: false
  addons:
    default: ''
    description: Comma-separated list of addons (i.e. metrics-server,registry,ingress,dashboard)
    required: false
  auto-update-drivers:
    default: 'false'
    description: Automatically updates drivers to the latest version
    required: false
  delete-on-failure:
    default: 'true'
    description: Delete the current cluster if start fails and try again
    required: false
  interactive:
    default: 'false'
    description: Allow user prompts for more information
    required: false
  wait:
    default: 'apiserver'
    description: Comma separated list of Kubernetes components to verify and wait for after starting a cluster
    required: false
  nodes:
    default: '1'
    description: Set number of cluster nodes
    required: false
  cpus:
    default: '2'
    description: Number of CPUs allocated to Kubernetes
    required: false
  memory:
    default: '3g'
    description: Number of CPUs allocated to Kubernetes
    required: false
  network-plugin:
    default: ''
    description: The name of the network plugin (i.e. 'cni')
    required: false
outputs:
  ip:
    description: Minikube IP
runs:
  using: node12
  main: dist/index.js
