name: Minikube Github Action
description: Setup Minikube and starts local cluster
author: hiberbee
branding:
  icon: anchor
  color: blue
inputs:
  version:
    default: '1.12.0'
    description: Set minikube version
    required: false
outputs: {}
runs:
  image: docker://hiberb/minikube:${{ inputs.version }}
  using: docker
