name: Minikube Github Action
description: Setup Minikube and starts local cluster
author: hiberbee
branding:
  icon: anchor
  color: blue
inputs:
  version:
    default: '1.12.0'
    description: Set minikube version
    required: false
  kubernetes-version:
    default: 'stable'
    description: Set Kubernetes version
    required: false
  nodes:
    default: '1'
    description: Set number of cluster nodes
    required: false
  cpus:
    default: '2'
    description: Number of CPUs allocated to Kubernetes
    required: false
  network-plugin:
    default: ''
    description: The name of the network plugin (i.e. 'cni')
    required: false
outputs: {}
runs:
  using: node12
  main: dist/index.js
