name: Minikube Github Action
description: Setup Minikube and starts local cluster
author: hiberbee
branding:
  icon: anchor
  color: blue
inputs:
  version:
    default: '1.12.1'
    description: Set minikube version
    required: false
  kubernetes-version:
    default: '1.18.6'
    description: Set Kubernetes version
    required: false
  profile:
    default: 'minikube'
    description: Set minikube profile name
    required: false
  addons:
    default: ''
    description: Comma-separated list of addons (i.e. metrics-server,registry,ingress,dashboard)
    required: false
  nodes:
    default: '1'
    description: Set number of cluster nodes
    required: false
  cpus:
    default: '2'
    description: Number of CPUs allocated to Kubernetes
    required: false
  network-plugin:
    default: ''
    description: The name of the network plugin (i.e. 'cni')
    required: false
outputs:
  ip:
    description: Minikube IP
runs:
  using: node12
  main: dist/index.js
